Emc/subgraph-containerisation
KlimaDAO/klima-subgraph pull request #139
Opened 2024-06-04 05:43 UTC by 0xemc

2024-07-10 15:38 UTC, psparacino commented on carbonmark/subgraph.yaml
> +      startBlock: 57748574
this should not be merged to main

2024-07-10 15:41 UTC, psparacino requested changes
all the subgraph.yamls block #s should remain unchanged when merging to main

2024-07-18 08:02 UTC, 0xemc commented on carbonmark/subgraph.yaml
> +      startBlock: 57748574
Sure thing, reverted.

2024-07-18 08:05 UTC, 0xemc commented
@cujowolf @0xAurelius @psparacino would appreciate another look at this.

2024-07-18 14:03 UTC, psparacino approved these changes
all looks good to me

2024-07-24 10:08 UTC, merged