add Retire entity update on c3 finalization
KlimaDAO/klima-subgraph pull request #169
Opened 2024-07-19 16:38 UTC by psparacino

2024-07-30 07:41 UTC, 0xemc submitted a review, later dismissed

2024-07-30 09:02 UTC, 0xAurelius requested changes

2024-07-30 09:02 UTC, 0xAurelius commented on polygon-digital-carbon/src/RetirementHandler.ts
> +      if (retireId === null) {
Are TypeScript object attributes `null` or `undefined` if they are not set?

I'm worried that `===` will not return `true` against an `undefined` value, but could just use `==` which will

![image](https://github.com/user-attachments/assets/eb773a96-4caa-4721-847b-b9ebe515d5b3)

![image](https://github.com/user-attachments/assets/9d6bb280-28b8-4486-ba75-e5844a8d4240)

2024-08-05 15:51 UTC, 0xAurelius approved these changes

2024-08-14 12:23 UTC, 0xemc approved these changes

2024-08-14 12:48 UTC, closed without merging