[`Pairs`] Adjust `currentPrice` and `currentPricePerTonne` to account for fee reduction
KlimaDAO/klima-subgraph pull request #174
Opened 2024-07-24 18:40 UTC by psparacino

CCO2 charges a fee in CC02 on retirement. Therefore the quoted price needs to take into account that subtraction so that the user is actually quoted for more(*) tonnes than their targeted retire amount.

ex:

1. retire 100 tonnes at a 10% fee
2. After the cco2 fee only 90 tonnes will actually be retired.
3. so --> 100 = .9 * x. Therefore the price for 100 tonnes of an actual retirement credited to the user is actually the price for 111.11 tonnes.
4. `currentprice`  for cco2 reflects this change.

Also added currentPriceInTonnes to standardize units with the api.

2024-07-24 20:09 UTC, cujowolf approved these changes

2024-08-23 04:43 UTC, must-be-carbon requested changes

2024-08-23 04:43 UTC, must-be-carbon commented on pairs/src/Pair.ts
> +      let transactionPercentage = BigDecimal.fromString(cco2_contract.transactionPercentage().toString())
This should be burning percentage. 

Currently we are not factoring in for the transactionPercentage.. as Coorest has decided to keep txnFee => 0. 

Note: transactionPercentage != burningPercentage..

2024-08-23 04:43 UTC, must-be-carbon commented on pairs/src/Pair.ts
> +      let transactionPercentage = BigDecimal.fromString(cco2_contract.transactionPercentage().toString())
Unless txnPercentage is used for any other purpose.

2024-08-23 14:34 UTC, must-be-carbon approved these changes

2024-08-27 16:21 UTC, merged